# This is a basic workflow to help you get started with Actions

name: Merge to publish branch

# Controls when the action will run. 
on:
  release:
    types: [published]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge-to-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Merge
      - name: Merge master to publish
        uses: devmasx/merge-branch@v1.3.1
        with:
          # 
          type: now
          # The name of target branch to merge
          target_branch: publish
          # Github token
          github_token: ${{secrets.GITHUB_TOKEN}}
